#Tax amount (decimal)
tax: 0.05
tax-account: tax

#If a player has the shop menu open, and says something that isn't a number, should we send it to chat?
always-chat: false

shop:
    #Cost to make a stall
    cost: 10
    refund: false
    lock: false
    sneak-only: false
    auto-sign: true
    pay-unlimited-shop-owners: false

plugins:
    #Whether or not to hook into these plugins, and stop players claiming chests as shops when they can't use the chest.
    preciousstones: true
    worldguard: true
    lockette: true
    griefprevention: true

#List of items to disallow selling of.  Anyone with quickshop.bypass.<itemID> can bypass it    
blacklist:
    - 7